audit_header: false
title: "Plymouth's Best Real Estate Training"
description: Kerby & Cristina Skurat, a top Real Estate Agent in Plymouth, shares his/her own internal real estate agent training for free. His/Her Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: http://kerbyandcristina.eventbrite.com/
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
  - title: About
    url: /about/
client:
  name: Kerby & Cristina Skurat
  title:
  license_number:
  about_markdown: |
    The husband and wife team of Kerby & Cristina Real Estate Experts of RE/MAX Results have built a business from the ground up. They have created one of the most premier real estate teams in the Minneapolis area. Being recognized consistently as the #1 RE/MAX Results Team in the nation. The team has personally served over 3,000 families the past decade and sells over 500+ homes annually.  Our biggest goal is to gain and retain lifetime clients who feel confident in reaching out to our team for all of their real estate needs.
  market: Plymouth
  brand: Kerby & Cristina Real Estate Experts
  brokerage: RE/MAX Results
  address: 1143 South Shore Drive Plymouth, MN 55441
  phone: 612-991-3466
  phone_type:
  phone2:
  phone2_type:
  email: kerby@kerbyandcristina.com
  url:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Kerby & Cristina Real Estate Experts can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KerbyandCristina?source=website
  linkedin_url: https://www.linkedin.com/company/kerby-&-cristina-real-estate-experts-of-re-max-results
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url: https://www.instagram.com/kcexperts
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Plymouth Real Estate Podcast with Kerby & Cristina Skurat'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Plymouth Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Kerby & Cristina Real Estate Experts - your professional Plymouth Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Plymouth, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Kerby & Cristina Skurat'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Plymouth Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#36578F'
  theme_color: '#898b8f'
  accent_color: '#ed1c24'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
